# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import python_code as module_0


def test_case_0():
    bool_0 = False
    float_0 = -540.0
    set_0 = {bool_0, bool_0, float_0, bool_0}
    module_0.listSpeechSynthesisTasks(set_0)
