# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import python_code as module_0


def test_case_0():
    bool_0 = False
    module_0.list_speech_synthesis_tasks(bool_0)
